sudo: false
language: python
branches:
  only:
    - master
python:
    - 2.7
    - 3.5
cache:
    directories:
        - $HOME/local/tgz
before_install:
    - mkdir -p $HOME/.python-eggs
    - chmod og-w $HOME/.python-eggs
    - bash dev/travis-prereqs.sh
    - pip install --upgrade pip pytest pytest-cov pep8 coverage codecov
install:
    - python setup.py install
before_script:
    - export PATH=$HOME/local/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/local/lib
    - make check
    - make style
    - set -eo pipefail
script: make test testmore
after_success:
    - codecov
