language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
addons:
    apt:
        packages:
            - genometools
before_install:
    - wget -P $HOME https://github.com/standage/AEGeAn/archive/master.tar.gz
    - tar -xzf $HOME/master.tar.gz
    - cd $HOME/AEGeAn-master && make
    - make depend
before_script:
    - export PATH=$HOME/AEGeAn-master/bin:$HOME/AEGeAn-master/data/script:$PATH
    - make check-dev
script: make test
