sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
cache:
    directories:
        - $HOME/local/tgz
before_install:
    - mkdir -p $HOME/.python-eggs
    - chmod og-w $HOME/.python-eggs
    - bash dev/travis-prereqs.sh
install:
    - python setup.py install
before_script:
    - export LD_LIBRARY_PATH=$HOME/local/lib
    - make check-dev
    - set -eo pipefail
script: make test testmore
